[package]
name = "rrtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[features]
std = []
PIDController = []
PIDControllerShift = ["std"]
State = []
Encoder = ["State"]
MotorMode = []
Motor = ["PIDControllerShift", "Encoder", "MotorMode"]
MotionProfile = ["State"]
Task = ["std"]
default = ["Motor", "MotionProfile"]
