# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2024-2026 UxuginPython

[package]
name = "rrtk"
version = "0.7.0-beta.3"
license = "BSD-3-Clause"
edition = "2024"
rust-version = "1.95"
authors = ["UxuginPython <blinker-hazy-ultra at duck dot com>"]
homepage = "http://rrtk.org/crate/rrtk"
repository = "https://github.com/UxuginPython/rrtk"
description = "Rust Robotics ToolKit: A data flow-based robotics framework designed for embedded systems."
keywords = ["robotics", "control", "stream", "device", "dimensional-analysis"]
categories = ["science::robotics", "embedded", "no-std::no-alloc"]
# We can't exclude the SVGs because they're needed for building the docs.
exclude = ["/generatetestall.py", "/testall.sh", "/testallmiri.sh", "/checkall.sh", "/featurequickcheck.sh", "/exclude/"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libm = { version = ">=0.1, <0.3", default-features = false, optional = true }
micromath = { version = ">=1.0.1, <3", default-features = false, optional = true }
[features]
alloc = []
std = ["alloc", "internal_enhanced_float"]
devices = []
libm = ["dep:libm", "internal_enhanced_float"]
micromath = ["dep:micromath", "internal_enhanced_float"]
internal_enhanced_float = []
default = ["std"]
[lints.rust]
missing_docs = "warn"
[lints.clippy]
alloc_instead_of_core = "deny"
std_instead_of_core = "deny"
std_instead_of_alloc = "deny"
[package.metadata.docs.rs]
all-features = true
