[package]
name = "rrtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[features]
PIDController = []
PIDControllerShift = []
State = []
Encoder = ["State"]
MotorMode = []
Motor = ["PIDControllerShift", "Encoder", "MotorMode"]
MotionProfile = ["State"]
default = ["Motor", "MotionProfile"]
